# esto es para traer conecciones
version: "3"

services: 
    web:
        container_name: aplicaionconmongo
        restart: always
        build: .
        ports: 
            - "5000:3000"
        links: 
            - mongoexpress

        mongoexpress:
            image: mongo-express
            ports:
                - "8081:8081"
            links:
                - mongo
        mongo:
            image: mongo
            
            