CREATE TABLE IF NOT EXISTS projects(
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
nombre TEXT NOT NULL CHECK (nombre <> ''),
prioridad integer NOT NULL,
descripcion text,
fecha_entrega date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
nombre TEXT NOT NULL CHECK (nombre <> ''),
estado BOOLEAN,
projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(nombre,prioridad,descripcion,fecha_entrega)
    VALUES('HACER UNA APLICAION WEB',1,"USANDO JAVASCRIPT","2021-05-12");

INSERT INTO projects(nombre,prioridad,descripcion,fecha_entrega)
    VALUES('demo de robot',2,'fallo mi pinche robot','2021-04-11');


--insertando datos para las tareas
INSERT INTO tasks(nombre,estado,projectId)
    VALUES('bañar a daxzel',false,2);

INSERT INTO tasks(nombre,estado,projectId)
    VALUES('jugar dotita',true,1);

INSERT INTO tasks(nombre,estado,projectId)
    VALUES('carga a papanel',false,2);

INSERT INTO tasks(nombre,estado,projectId)
    VALUES('carga el celular',true,1);
    

